@startuml

title Notifier Component Diagram

!define ASYNC_TASK_COLOR #LightBlue
!define SYNC_TASK_COLOR #LightCyan
!define QUEUE_COLOR #LightGreen
skinparam frame {
    BackgroundColor ASYNC_TASK_COLOR
}
skinparam component {
    BackgroundColor ASYNC_TASK_COLOR
    Style Rectangle
}
skinparam queue {
    BackgroundColor QUEUE_COLOR
}

() user
component [Tracer] as Tracer
frame "AsyncWatcher" as AsyncWatcher{
    component [SyncWatcher] as SyncWatcher SYNC_TASK_COLOR
}
component [Core] as Core

queue "CancellationQ" as CancellationQ
user --> CancellationQ : tx
CancellationQ --> AsyncWatcher : rx

queue "EventQ" as EventQ
SyncWatcher --> EventQ : tx
EventQ --> Core : rx

queue "CommandQ" as CommandQ
Core --> CommandQ : tx
CommandQ --> AsyncWatcher : rx

queue "TracerQ" as TracerQ
AsyncWatcher --> TracerQ : tx
SyncWatcher --> TracerQ : tx
Core --> TracerQ : tx
TracerQ --> Tracer : rx

queue "Queue A" as QA
queue "Queue B" as QB
queue "Queue C" as QC

component [Syncjob A] as SyncJobA
component [Syncjob B] as SyncJobB
component [Syncjob C] as SyncJobC

Core --> QA : tx
Core --> QB : tx
Core --> QC : tx

QA --> SyncJobA : rx
QB --> SyncJobB : rx
QC --> SyncJobC : rx

SyncJobA --> TracerQ : tx

note top of Core
    Central task that
    publishes notifications
    to multiple mpsc queues
end note

note top of QC
    Each mpsc syncjob
    queue is consumed
    by exactly one task
end note

note right of CancellationQ
    The user sends a cancellation signal to the AsyncWatcher, which then gracefully shuts
    down the SyncWatcher. When this happens the EventQ is closed, which causes the Core to
    stop consuming events and exit. After Core exits, all the SyncJob queues are also closed
    and also are the SyncJobs. Finally, since no tx is still alive, the TracerQ is closed
    and so is the Tracer.
end note

@enduml
